version: "2.2"

services:
  fleet:
    depends_on:
      esmonitoring01:
        condition: service_healthy
      kibmonitoring01:
        condition: service_healthy
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    networks:
      - elk
    volumes:
      - monitoring_certs:/usr/share/elastic-agent/config/certs
    container_name: fleet
    ports:
      - ${FLEET_PORT}:8220
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_CERT=/usr/share/elastic-agent/config/certs/fleet/fleet.crt
      - FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/config/certs/fleet/fleet.key
      - FLEET_SERVER_HOST=0.0.0.0
      - FLEET_SERVER_PORT=8220
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
      - FLEET_ENROLL=1
      - KIBANA_FLEET_SETUP=1
      - KIBANA_FLEET_HOST=https://kibmonitoring01:5601
      - ELASTICSEARCH_HOST=https://esmonitoring01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_CA=/usr/share/elastic-agent/config/certs/ca/ca.crt
      - FLEET_URL=https://fleet:8220
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I --cacert config/certs/ca/ca.crt https://fleet:8220 | grep -q 'HTTP/2 404'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  
  agent:
    image: docker.elastic.co/beats/elastic-agent:${STACK_VERSION}
    volumes:
      - monitoring_certs:/usr/share/elastic-agent/config/certs
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: agent
    networks:
      - elk
    ports:
      - ${AGENT_PORT}:8220
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      - FLEET_ENROLLMENT_TOKEN=${AGENT_TOKEN}
      - FLEET_ENROLL=1
      - FLEET_CA=/usr/share/elastic-agent/config/certs/fleet/fleet.crt
      - FLEET_URL=https://fleet:8220
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://agent:8220 | grep -q 'HTTP/2 404'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
