version: "2.2"

services:

  metricbeat01:
    depends_on:
      es01:
        condition: service_healthy
      esmonitoring01:
        condition: service_healthy
      kibana:
        condition: service_healthy
      kibmonitoring01:
        condition: service_healthy
    image: docker.elastic.co/beats/metricbeat:${STACK_VERSION}
    user: root
    command: ["run", "-e", "--strict.perms=false"]
    networks:
      - elk
    volumes:
      - metricbeatdata01:/usr/share/metricbeat/data
      - "./metricbeat_monitoring.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
      - "/proc:/hostfs/proc:ro"
      - "/:/hostfs:ro"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  filebeat01:
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
    command: ["run", "-e", "--strict.perms=false"]
    user: root
    networks:
      - elk
    volumes:
      - certs:/usr/share/filebeat/certs
      - filebeatdata01:/usr/share/filebeat/data
      - "./filebeat_monitoring.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

volumes:
  metricbeatdata01:
    driver: local
  filebeatdata01:
    driver: local