metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["https://es01:9200", "https://es02:9200", "https://es03:9200"]
  username: "elastic"
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    verification_mode: none

- module: kibana
  metricsets: 
    - stats
  period: 10s
  hosts: "https://kibana:5601"
  username: "elastic"
  password: ${ELASTIC_PASSWORD}
  xpack.enabled: true
  ssl:
    enabled: true
    verification_mode: none

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

setup.kibana:
  host: "https://kibmonitoring01:5601"
  username: "elastic"
  password: ${KIBANA_PASSWORD} 

output.elasticsearch:
  hosts: ["https://esmonitoring01:9200"]
  username: "elastic"
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    verification_mode: none